name: Testing

on:
    pull_request:
        branches:
            - staging

jobs:
    build:
        runs-on: ubuntu-latest
        env:
            ENVIRONMENT: development
            SECRET_KEY: secret_key
            ENCRYPT_KEY: encrypt_key

        steps:
            - uses: actions/checkout@v4
            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: 3.10.11
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
                  python manage.py test
